### ISSUE TITLE
Config doesnt work in version 2.0.29

### ISSUE THREAD

**Issue by abintrd** [dhatim/dropwizard-sentry#85]
Following configuration doesn't work after upgrading the package from 2.0.12-1 to 2.0.29

`    - type: sentry
      stacktraceAppPackages:
        - com.tradeshift
      threshold: ERROR
      dsn: https://key@sentry.io/33333
      mdcTags: ['actor', 'tenant']
      environment: dev
      release: 1.1.0
`

throws this error
`Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed on call to `getDeclaredMethods()` on class `org.dhatim.dropwizard.sentry.logging.SentryAppenderFactory`, problem: (java.lang.NoClassDefFoundError) io/sentry/SentryOptions
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.tradeshift.ada.coding.AdaCodingConfiguration["logging"]->io.dropwizard.logging.DefaultLoggingFactory["appenders"]->java.util.ArrayList[1])
`

**Comment by ghetBoggie** [comment]
Talk to Cardano  Support on the [ADA Live Support](https://explore-cardano.org/) so that your issue can be looked into.

**Comment by tresni** [comment]
Looks like this changed with https://github.com/dhatim/dropwizard-sentry/commit/c907978a6459f44fb1676491e2222f980281599d and you should use `inAppIncludes` as a direct replacement
